import {
	getMetricInfoById,
	type AssessmentMetricResult,
	type CustomMetricLlmFeedback,
	type ProfileLlmFeedback,
} from './runAssessment';
import {
	buildWebviewContentSecurityPolicy,
	createWebviewNonce,
	escapeHtml,
	safeWebviewImageUrl,
} from './webviewSecurity';
import { renderExplanationHtml, renderTargetLink } from './webviewFormatting';
import type { HistoryComparisonContent } from './historyRendering';

function profileFeedbackStatus(status: string): { className: string; label: string; icon: string } {
	switch (status) {
		case 'achieved': return { className: 'achieved', label: 'Goal achieved', icon: '✓' };
		case 'not-achieved': return { className: 'not-achieved', label: 'Goal not achieved', icon: '×' };
		case 'partial': return { className: 'partial', label: 'Partially achieved', icon: '◐' };
		case 'observed': return { className: 'observed', label: 'Change observed', icon: '↕' };
		case 'unchanged': return { className: 'unchanged', label: 'No meaningful change', icon: '—' };
		default: return { className: 'not-comparable', label: 'Not comparable', icon: '?' };
	}
}

/** Render validated, structured profile guidance without interpreting model output as HTML. */
export function renderProfileLlmFeedback(feedback: ProfileLlmFeedback): string {
	const status = profileFeedbackStatus(feedback.goalStatus);
	const changes = Array.isArray(feedback.changes)
		? feedback.changes.filter((item): item is string => typeof item === 'string' && Boolean(item.trim())).slice(0, 3)
		: [];
	const suggestions = Array.isArray(feedback.suggestions)
		? feedback.suggestions.filter((item) => item && typeof item.title === 'string' && typeof item.action === 'string').slice(0, 4)
		: [];
	const sourceFiles = Array.isArray(feedback.sourceFiles)
		? feedback.sourceFiles.filter((item): item is string => typeof item === 'string' && Boolean(item.trim())).slice(0, 10)
		: [];
	const sourceLabel = feedback.sourceContextUsed && sourceFiles.length > 0
		? `Based on metrics and ${sourceFiles.length} source file${sourceFiles.length === 1 ? '' : 's'}`
		: 'Based on metrics only';
	const changesHtml = changes.length > 0
		? `<div class="feedback-changes">${changes.map((change) => `<div class="change-chip"><span aria-hidden="true">↳</span><span>${escapeHtml(change)}</span></div>`).join('')}</div>`
		: '';
	const suggestionsHtml = suggestions.length > 0
		? `<div class="suggestion-grid">${suggestions.map((suggestion, index) => {
			const files = Array.isArray(suggestion.files)
				? suggestion.files.filter((item): item is string => typeof item === 'string' && Boolean(item.trim())).slice(0, 4)
				: [];
			return `<article class="suggestion-card">
				<div class="suggestion-number">${index + 1}</div>
				<div><h3>${escapeHtml(suggestion.title)}</h3><p class="suggestion-action">${escapeHtml(suggestion.action)}</p>${suggestion.rationale ? `<p class="suggestion-rationale">Why: ${escapeHtml(suggestion.rationale)}</p>` : ''}${files.length > 0 ? `<div class="file-chips">${files.map((file) => `<code>${escapeHtml(file)}</code>`).join('')}</div>` : ''}</div>
			</article>`;
		}).join('')}</div>`
		: '<p class="no-suggestions">No code suggestions were returned for this assessment.</p>';

	return `<section class="profile-ai-feedback status-${status.className}" aria-labelledby="profile-ai-title">
		<div class="profile-ai-heading">
			<div class="profile-ai-icon" aria-hidden="true">${status.icon}</div>
			<div><span class="eyebrow">Generated by AI</span><h2 id="profile-ai-title">AI-generated explanation</h2><p class="profile-ai-goal">${escapeHtml(feedback.goalTitle || 'Profile assessment')}</p></div>
			<span class="profile-ai-status">${status.label}</span>
		</div>
		<p class="profile-ai-summary">${escapeHtml(feedback.summary)}</p>
		${changesHtml}
		<div class="suggestions-heading"><h3>Suggested next steps</h3><span class="context-badge" title="Source context supplied to the configured LLM provider">${escapeHtml(sourceLabel)}</span></div>
		${suggestionsHtml}
		<p class="ai-note">AI-generated suggestions. Validate changes against the profile goal and metric results below.</p>
	</section>`;
}

/** Render validated custom-metric analysis as an evidence-to-action sequence. */
export function renderCustomMetricLlmFeedback(feedback: CustomMetricLlmFeedback): string {
	const findings = Array.isArray(feedback.findings)
		? feedback.findings.filter((item) => item
			&& typeof item.title === 'string'
			&& typeof item.observation === 'string'
			&& typeof item.interpretation === 'string'
			&& typeof item.recommendation === 'string').slice(0, 6)
		: [];
	const materialChangeCount = Number.isInteger(feedback.materialChangeCount) && feedback.materialChangeCount >= 0
		? feedback.materialChangeCount
		: 0;
	const sourceFiles = Array.isArray(feedback.sourceFiles)
		? feedback.sourceFiles.filter((item): item is string => typeof item === 'string' && Boolean(item.trim())).slice(0, 10)
		: [];
	const sourceLabel = feedback.sourceContextUsed && sourceFiles.length > 0
		? `Based on metrics and ${sourceFiles.length} source file${sourceFiles.length === 1 ? '' : 's'}`
		: 'Based on metrics only';
	const modeLabel = feedback.analysisMode === 'comparison'
		? `Baseline comparison · ${materialChangeCount} material change${materialChangeCount === 1 ? '' : 's'}`
		: 'Current-state analysis';
	const findingCards = findings.length > 0
		? `<div class="custom-finding-list">${findings.map((finding, index) => {
			const metricIds = Array.isArray(finding.metricIds)
				? finding.metricIds.filter((item): item is string => typeof item === 'string' && Boolean(item.trim())).slice(0, 6)
				: [];
			const files = Array.isArray(finding.files)
				? finding.files.filter((item): item is string => typeof item === 'string' && Boolean(item.trim())).slice(0, 4)
				: [];
			return `<article class="custom-finding-card">
				<div class="custom-finding-index" aria-hidden="true">${index + 1}</div>
				<div class="custom-finding-content">
					<div class="custom-finding-heading"><h3>${escapeHtml(finding.title)}</h3>${metricIds.length > 0 ? `<div class="metric-chips">${metricIds.map((metricId) => `<span>${escapeHtml(metricId)}</span>`).join('')}</div>` : ''}</div>
					<div class="analysis-step evidence-step"><span class="analysis-step-label">Measured evidence</span><p>${escapeHtml(finding.observation)}</p></div>
					<div class="analysis-connector" aria-hidden="true">↓</div>
					<div class="analysis-step interpretation-step"><span class="analysis-step-label">Technical interpretation</span><p>${escapeHtml(finding.interpretation)}</p></div>
					<div class="analysis-connector" aria-hidden="true">↓</div>
					<div class="analysis-step recommendation-step"><span class="analysis-step-label">Practical next step</span><p>${escapeHtml(finding.recommendation)}</p>${files.length > 0 ? `<div class="file-chips">${files.map((file) => `<code>${escapeHtml(file)}</code>`).join('')}</div>` : ''}</div>
				</div>
			</article>`;
		}).join('')}</div>`
		: feedback.analysisMode === 'comparison'
			? `<div class="custom-no-findings"><strong>No material metric changes identified</strong><p>The comparison did not meet the fixed reporting thresholds. Review the metric results below if smaller changes are relevant to the current engineering objective.</p></div>`
			: `<div class="custom-no-findings"><strong>No structured findings returned</strong><p>This assessment has no compatible baseline. Use the current metric values below as the reference point for a subsequent comparison.</p></div>`;

	return `<section class="custom-ai-feedback" aria-labelledby="custom-ai-title">
		<div class="custom-ai-heading">
			<div class="custom-ai-icon" aria-hidden="true">AI</div>
			<div class="custom-ai-title"><span class="custom-eyebrow">Generated by AI</span><h2 id="custom-ai-title">AI-generated technical explanation</h2></div>
			<div class="custom-ai-badges"><span class="analysis-mode-badge">${modeLabel}</span><span class="context-badge" title="Source context supplied to the configured LLM provider">${escapeHtml(sourceLabel)}</span></div>
		</div>
		<p class="custom-ai-summary">${escapeHtml(feedback.summary)}</p>
		<div class="custom-analysis-key"><span><i class="key-evidence"></i>Observation</span><span><i class="key-interpretation"></i>Interpretation</span><span><i class="key-recommendation"></i>Practical action</span></div>
		${findingCards}
		<p class="ai-note">AI-generated technical analysis. Confirm implemented changes against the metric values and project requirements.</p>
	</section>`;
}

export function generateResultsHtml(
	results: AssessmentMetricResult[],
	url: string,
	isComplete: boolean = true,
	explanation?: string | null,
	explanationError?: string,
	profileFeedback?: ProfileLlmFeedback,
	customFeedback?: CustomMetricLlmFeedback,
	comparison?: HistoryComparisonContent,
): string {
	const inputResults = Array.isArray(results) ? results : [];
	const imageUrls = new Set<string>();
	// Filter out results that are completely empty, but keep them if they are the only ones for a metric
	const filteredResults = inputResults.filter((r, i) => {
		if (Array.isArray(r?.results) && r.results.length > 0) {
			return true;
		}
		// If it's empty, check if there's any other non-empty result for the same metric_id
		const hasNonEmpty = inputResults.some((other, j) =>
			i !== j &&
			other?.metric_id === r?.metric_id &&
			Array.isArray(other.results) &&
			other.results.length > 0
		);
		return !hasNonEmpty;
	});

	const resultItems = (filteredResults.length > 0 ? filteredResults : []).map((r) => {
		const metricId = typeof r?.metric_id === 'string' ? r.metric_id : 'Unknown metric';
		const metric = getMetricInfoById(metricId);
		const metricName = metric?.name || metricId;
		const resultValues = Array.isArray(r?.results) ? r.results : [r?.results];

		return `
		<div class="metric-result">
			<h3>${escapeHtml(metricName)}</h3>
			<div class="result-values">
				${resultValues.map((val: unknown, i: number) => {
			let displayVal = '';
			const imageUrl = safeWebviewImageUrl(val);
			if (imageUrl) {
				imageUrls.add(imageUrl);
				const safeImageUrl = escapeHtml(imageUrl);
				displayVal = `<a class="image-zoom-link" href="${safeImageUrl}" target="_blank" rel="noopener noreferrer" aria-label="Open result ${i + 1} image at full size" title="Open full-size image"><img class="result-image" src="${safeImageUrl}" alt="Result ${i + 1} visual output" /></a>`;
			} else if (typeof val === 'object' && val !== null) {
				let serialized: string;
				try {
					serialized = JSON.stringify(val, null, 2) ?? String(val);
				} catch {
					serialized = '[Result could not be serialized]';
				}
				displayVal = `<pre class="result-json">${escapeHtml(serialized)}</pre>`;
			} else {
				displayVal = escapeHtml(String(val ?? ''));
			}
			return `<div class="result-item"><strong>Result ${i + 1}:</strong> ${displayVal}</div>`;
		}).join('')}
			</div>
		</div>
		`;
	}).join('');
	const explanationHtml = profileFeedback
		? renderProfileLlmFeedback(profileFeedback)
		: customFeedback
			? renderCustomMetricLlmFeedback(customFeedback)
			: explanationError
				? `<section class="ai-explanation unavailable"><h2>AI explanation unavailable</h2><p>${escapeHtml(explanationError)} The assessment results are still shown below.</p></section>`
				: explanation === undefined ? '' : explanation
					? `<section class="ai-explanation"><span class="ai-eyebrow">Generated by AI</span><h2>AI-generated explanation</h2>${renderExplanationHtml(explanation)}<p class="ai-note">AI-generated interpretation. Verify important decisions against the metric values below.</p></section>`
					: `<section class="ai-explanation unavailable"><h2>AI-generated explanation</h2><p>${escapeHtml(explanationError || 'The AI explanation is unavailable.')} The assessment results are still shown below.</p></section>`;
	const nonce = createWebviewNonce();
	for (const imageUrl of comparison?.imageUrls ?? []) {
		imageUrls.add(imageUrl);
	}
	const contentSecurityPolicy = buildWebviewContentSecurityPolicy(nonce, imageUrls);
	const comparisonHtml = comparison
		? `<details class="comparison-block">
			<summary class="comparison-summary"><span class="comparison-summary-copy"><span class="comparison-summary-title">Comparison details</span><span class="comparison-summary-subtitle">Baseline versus current assessment</span></span><span class="comparison-preview">${comparison.comparisonSummaryHtml}</span><span class="comparison-toggle" aria-hidden="true">▶</span></summary>
			<div class="comparison-content">${comparison.comparisonHtml}</div>
		</details>`
		: '';
	const rawMetricsHtml = `<details class="raw-metrics"${isComplete ? '' : ' open'}>
		<summary><span class="raw-metrics-label">Raw metrics</span><span class="raw-metrics-actions"><span class="results-count">${filteredResults.length} ${filteredResults.length === 1 ? 'metric' : 'metrics'}</span><span class="raw-metrics-toggle" aria-hidden="true">▶</span></span></summary>
		<div class="raw-metrics-content">
			${resultItems.length > 0 ? resultItems : '<div class="empty-state"><p>No results available yet. Please try again.</p></div>'}
		</div>
	</details>`;

	return `<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-Security-Policy" content="${escapeHtml(contentSecurityPolicy)}">
	<title>Evaluation Results</title>
	<style nonce="${nonce}">
		:root {
			--canvas: #f1f4f6;
			--surface: #ffffff;
			--surface-subtle: #eef3f5;
			--surface-accent: #e5f3f0;
			--surface-muted: #e4eaee;
			--surface-comparison: #dcecf3;
			--surface-warning: #fff8e9;
			--surface-llm: #fbf9f3;
			--surface-comparison-block: #edf5f8;
			--surface-evidence: #edf0f2;
			--surface-interpretation: #e8f2f7;
			--surface-recommendation: #e5f3f0;
			--step-evidence: #60717b;
			--step-interpretation: #1f688c;
			--step-recommendation: #0b746f;
			--ink: #101b24;
			--ink-soft: #334550;
			--muted: #52626d;
			--header: #102f46;
			--navy: #12364f;
			--navy-light: #1f5875;
			--heading: #12364f;
			--accent: #0b746f;
			--accent-strong: #075e5a;
			--accent-soft: #d2ebe7;
			--comparison: #2d708f;
			--comparison-strong: #1d5874;
			--border: #bcc9d1;
			--success: #14774f;
			--danger: #aa3434;
			--warning: #96600f;
			--llm: #7a694d;
		}
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
		}
		body {
			font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
			background: var(--canvas);
			min-height: 100vh;
			padding: 28px 20px;
			color: var(--ink);
		}
		.container {
			max-width: 960px;
			margin: 0 auto;
			background: var(--surface);
			border: 1px solid var(--border);
			border-radius: 10px;
			box-shadow: 0 16px 40px rgba(16, 47, 70, .18);
			overflow: hidden;
		}
		.header {
			background: var(--header);
			color: white;
			padding: 28px 30px 30px;
			border-bottom: 5px solid var(--accent);
		}
		.header h1 {
			font-size: 30px;
			font-weight: 650;
			letter-spacing: -.02em;
			margin-bottom: 8px;
		}
		.header p {
			color: #cbd7df;
			font-size: 15px;
		}
		.assessment-status { display: flex; align-items: center; gap: 7px; }
		.status-dot { width: 8px; height: 8px; border-radius: 50%; background: #69c7a2; box-shadow: 0 0 0 3px rgba(105, 199, 162, .14); }
		.assessment-status.in-progress .status-dot { background: #e7b75d; box-shadow: 0 0 0 3px rgba(231, 183, 93, .14); }
		.url-display {
			background: rgba(255, 255, 255, .08);
			border: 1px solid rgba(255, 255, 255, .28);
			border-left: 4px solid #65c9bd;
			padding: 10px 13px;
			border-radius: 6px;
			margin-top: 16px;
			word-break: break-all;
			font-size: 13px;
			font-family: 'SFMono-Regular', Consolas, monospace;
			color: #edf5f7;
		}
		.target-link { color: #fff; font-weight: 600; text-decoration-color: #65c9bd; text-decoration-thickness: 1.5px; text-underline-offset: 3px; }
		.target-link:hover { color: #bff3ec; text-decoration-thickness: 2px; }
		.target-link:focus-visible { border-radius: 2px; outline: 2px solid #8de0d5; outline-offset: 3px; }
		.content {
			padding: 30px;
		}
		.ai-explanation {
			margin-bottom: 24px;
			padding: 20px;
			border: 1px solid #e3dccd;
			border-left: 5px solid var(--llm);
			border-radius: 7px;
			background: var(--surface-llm);
			line-height: 1.6;
		}
		.ai-explanation h2 { margin-bottom: 12px; color: var(--navy); font-size: 20px; }
		.ai-eyebrow { display: block; margin-bottom: 3px; color: var(--llm); font-size: 11px; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; }
		.ai-explanation h3 { margin: 14px 0 6px; font-size: 16px; }
		.ai-explanation p { margin: 0 0 10px; }
		.ai-explanation ul, .ai-explanation ol { margin: 0 0 10px 22px; }
		.ai-explanation code { padding: 1px 4px; border-radius: 3px; background: rgba(23, 53, 77, .08); }
		.ai-explanation p:last-child { margin-bottom: 0; }
		.ai-explanation.unavailable { background: var(--surface-warning); border-color: var(--warning); }
		.ai-note { color: var(--muted); font-size: 12px; }
		.profile-ai-feedback {
			margin-bottom: 26px;
			padding: 22px;
			border: 1px solid #e3dccd;
			border-top: 5px solid var(--accent);
			border-radius: 10px;
			background: var(--surface-llm);
		}
		.profile-ai-feedback.status-achieved { border-top-color: var(--success); }
		.profile-ai-feedback.status-not-achieved { border-top-color: var(--danger); }
		.profile-ai-feedback.status-partial { border-top-color: var(--warning); }
		.profile-ai-heading { display: grid; grid-template-columns: auto 1fr auto; align-items: center; gap: 12px; }
		.profile-ai-heading .eyebrow { color: var(--accent-strong); font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
		.profile-ai-heading h2 { margin-top: 3px; color: var(--navy); font-size: 20px; }
		.profile-ai-goal { margin-top: 4px; color: var(--muted); font-size: 12px; font-weight: 600; }
		.profile-ai-icon { display: grid; place-items: center; width: 38px; height: 38px; border-radius: 50%; background: var(--accent); color: white; font-size: 21px; font-weight: 700; }
		.status-achieved .profile-ai-icon { background: var(--success); }
		.status-not-achieved .profile-ai-icon { background: var(--danger); }
		.status-partial .profile-ai-icon { background: var(--warning); }
		.profile-ai-status, .context-badge { padding: 5px 9px; border-radius: 999px; background: var(--accent-soft); color: var(--accent-strong); font-size: 12px; font-weight: 700; white-space: nowrap; }
		.status-achieved .profile-ai-status { background: #def2e8; color: #176a49; }
		.status-not-achieved .profile-ai-status { background: #f9e5e5; color: #963838; }
		.status-partial .profile-ai-status { background: #faedcf; color: #87550e; }
		.profile-ai-summary { margin: 18px 0 14px; font-size: 16px; line-height: 1.55; color: var(--ink-soft); }
		.feedback-changes { display: grid; gap: 8px; margin-bottom: 20px; }
		.change-chip { display: grid; grid-template-columns: auto 1fr; gap: 8px; padding: 9px 11px; border-radius: 6px; background: var(--surface-muted); color: var(--ink-soft); font-size: 13px; line-height: 1.45; }
		.change-chip > span:first-child { color: var(--muted); font-weight: 700; }
		.suggestions-heading { display: flex; justify-content: space-between; align-items: center; gap: 12px; margin: 18px 0 10px; }
		.suggestions-heading h3 { color: var(--navy); font-size: 16px; }
		.context-badge { background: var(--surface-muted); color: var(--ink-soft); font-weight: 600; }
		.suggestion-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 11px; margin-bottom: 14px; }
		.suggestion-card { display: grid; grid-template-columns: auto 1fr; gap: 11px; padding: 14px; border: 1px solid var(--border); border-radius: 8px; background: var(--surface); }
		.suggestion-number { display: grid; place-items: center; width: 26px; height: 26px; border-radius: 7px; background: var(--accent); color: white; font-size: 12px; font-weight: 700; }
		.suggestion-card h3 { margin: 2px 0 6px; color: var(--navy-light); font-size: 14px; }
		.suggestion-action { color: var(--ink); font-size: 13px; line-height: 1.45; }
		.suggestion-rationale { margin-top: 7px; color: var(--muted); font-size: 12px; line-height: 1.4; }
		.file-chips { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 9px; }
		.file-chips code { max-width: 100%; overflow: hidden; padding: 3px 6px; border-radius: 4px; background: var(--surface-muted); color: var(--ink-soft); font-size: 11px; text-overflow: ellipsis; white-space: nowrap; }
		.no-suggestions { margin-bottom: 14px; color: var(--muted); font-size: 13px; }
		.profile-ai-feedback .ai-note { margin-top: 4px; }
		.custom-ai-feedback { margin-bottom: 26px; padding: 22px; border: 1px solid #e3dccd; border-top: 5px solid var(--llm); border-radius: 10px; background: var(--surface-llm); }
		.custom-ai-heading { display: grid; grid-template-areas: "icon title" "icon badges"; grid-template-columns: auto minmax(0, 1fr); align-items: start; column-gap: 12px; row-gap: 8px; }
		.custom-ai-title { grid-area: title; min-width: 0; }
		.custom-ai-badges { display: flex; grid-area: badges; flex-wrap: wrap; justify-content: flex-start; gap: 6px; }
		.custom-ai-icon { display: grid; grid-area: icon; width: 40px; height: 40px; place-items: center; border-radius: 9px; background: var(--navy-light); color: #fff; font-size: 12px; font-weight: 800; letter-spacing: .04em; }
		.custom-eyebrow { color: var(--accent-strong); font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
		.custom-ai-heading h2 { margin-top: 3px; color: var(--navy); font-size: 20px; }
		.analysis-mode-badge { padding: 5px 9px; border-radius: 999px; background: var(--accent-soft); color: var(--accent-strong); font-size: 12px; font-weight: 700; white-space: nowrap; }
		.custom-ai-summary { margin: 18px 0 14px; color: var(--ink-soft); font-size: 16px; line-height: 1.55; }
		.custom-analysis-key { display: flex; flex-wrap: wrap; gap: 8px 16px; margin-bottom: 14px; padding: 9px 11px; border-radius: 6px; background: var(--surface-muted); color: var(--muted); font-size: 11px; }
		.custom-analysis-key i { display: inline-block; width: 8px; height: 8px; margin-right: 5px; border-radius: 50%; }
		.key-evidence { background: var(--step-evidence); }
		.key-interpretation { background: var(--step-interpretation); }
		.key-recommendation { background: var(--step-recommendation); }
		.custom-finding-list { display: grid; gap: 12px; margin-bottom: 14px; }
		.custom-finding-card { display: grid; grid-template-columns: auto 1fr; gap: 12px; padding: 16px; border: 1px solid var(--border); border-radius: 9px; background: var(--surface); }
		.custom-finding-index { display: grid; width: 28px; height: 28px; place-items: center; border-radius: 7px; background: var(--navy-light); color: #fff; font-size: 12px; font-weight: 700; }
		.custom-finding-content { min-width: 0; }
		.custom-finding-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; margin: 2px 0 12px; }
		.custom-finding-heading h3 { color: var(--navy); font-size: 15px; line-height: 1.35; }
		.metric-chips { display: flex; flex: 0 0 auto; flex-wrap: wrap; justify-content: flex-end; gap: 4px; }
		.metric-chips span { padding: 3px 6px; border: 1px solid #bcd6d3; border-radius: 4px; background: var(--surface-accent); color: var(--accent-strong); font-family: 'SFMono-Regular', Consolas, monospace; font-size: 10px; font-weight: 700; }
		.analysis-step { padding: 10px 12px; border-left: 3px solid; border-radius: 5px; }
		.analysis-step-label { display: block; margin-bottom: 4px; font-size: 10px; font-weight: 800; letter-spacing: .06em; text-transform: uppercase; }
		.analysis-step p { color: var(--ink); font-size: 13px; line-height: 1.5; }
		.evidence-step { border-color: var(--step-evidence); background: var(--surface-evidence); }
		.evidence-step .analysis-step-label { color: var(--step-evidence); }
		.interpretation-step { border-color: var(--step-interpretation); background: var(--surface-interpretation); }
		.interpretation-step .analysis-step-label { color: var(--step-interpretation); }
		.recommendation-step { border-color: var(--step-recommendation); background: var(--surface-recommendation); }
		.recommendation-step .analysis-step-label { color: var(--step-recommendation); }
		.analysis-connector { height: 17px; padding-left: 14px; color: #8a969e; font-size: 13px; line-height: 17px; }
		.custom-no-findings { margin-bottom: 14px; padding: 14px; border: 1px solid var(--border); border-radius: 7px; background: var(--surface-subtle); }
		.custom-no-findings strong { display: block; margin-bottom: 4px; color: var(--navy); font-size: 14px; }
		.custom-no-findings p { color: var(--muted); font-size: 13px; line-height: 1.45; }
		.custom-ai-feedback .ai-note { margin-top: 4px; }
		.section-heading { display: flex; align-items: flex-end; justify-content: space-between; gap: 12px; margin: 30px 0 14px; }
		.section-heading h2 { color: var(--navy); font-size: 22px; }
		.section-heading p { color: var(--muted); font-size: 13px; }
		.comparison-block { margin-bottom: 28px; overflow: hidden; border: 1px solid #c7dce5; border-top: 5px solid var(--comparison); border-radius: 10px; background: var(--surface-comparison-block); }
		.comparison-summary { display: grid; grid-template-columns: minmax(150px, .75fr) minmax(280px, 1.5fr) auto; align-items: center; gap: 18px; padding: 18px 22px; cursor: pointer; list-style: none; }
		.comparison-summary::-webkit-details-marker { display: none; }
		.comparison-summary:hover { background: #e3f0f5; }
		.comparison-summary:focus-visible { outline: 2px solid var(--comparison); outline-offset: -3px; }
		.comparison-summary-copy, .comparison-summary-title, .comparison-summary-subtitle { display: block; }
		.comparison-summary-title { color: var(--navy); font-size: 21px; font-weight: 700; }
		.comparison-summary-subtitle { margin-top: 3px; color: var(--muted); font-size: 12px; font-weight: 500; }
		.comparison-preview { display: grid; grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr); align-items: center; gap: 9px; min-width: 0; }
		.comparison-preview-item, .comparison-preview-label, .comparison-preview-target { display: block; min-width: 0; }
		.comparison-preview-item { padding: 8px 10px; border: 1px solid #bdd4df; border-radius: 6px; background: rgba(255, 255, 255, .72); }
		.comparison-preview-label { margin-bottom: 3px; color: var(--comparison-strong); font-size: 9px; font-weight: 800; letter-spacing: .07em; text-transform: uppercase; }
		.comparison-preview-target { overflow: hidden; color: var(--ink-soft); font-size: 11px; font-weight: 600; text-overflow: ellipsis; white-space: nowrap; }
		.comparison-preview .target-link { color: var(--comparison-strong); text-decoration-color: #72a8bf; }
		.comparison-preview .target-link:hover { color: var(--navy); }
		.comparison-preview-arrow { color: var(--comparison); font-weight: 800; }
		.comparison-toggle { color: var(--comparison-strong); font-size: 14px; transition: transform .18s ease; }
		.comparison-block[open] .comparison-toggle { transform: rotate(90deg); }
		.comparison-block[open] .comparison-summary { border-bottom: 1px solid #c7dce5; }
		.comparison-content { padding: 18px 22px 22px; }
		.context { margin: 0 0 16px; padding: 11px 13px; border: 1px solid var(--border); border-radius: 6px; background: var(--surface-muted); color: var(--ink-soft); font-size: 13px; line-height: 1.5; }
		.run-pair { display: grid; grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr); align-items: stretch; gap: 10px; margin: 0 0 26px; }
		.run-chip { min-width: 0; padding: 14px 15px; border: 1px solid var(--border); border-top: 4px solid #82939d; border-radius: 7px; background: var(--surface-subtle); }
		.run-chip span { display: block; margin-bottom: 5px; color: var(--muted); font-size: 10px; font-weight: 800; letter-spacing: .07em; text-transform: uppercase; }
		.run-chip strong { display: block; overflow: hidden; color: var(--ink); font-size: 13px; font-weight: 650; line-height: 1.45; text-overflow: ellipsis; }
		.current-run { border-color: var(--comparison); background: var(--surface-comparison); }
		.current-run span { color: var(--comparison-strong); }
		.run-arrow { display: grid; width: 28px; place-items: center; color: var(--comparison); font-size: 20px; }
		.metric-section { margin: 0 0 20px; padding: 22px; border: 1px solid #c6d4db; border-left: 5px solid var(--comparison); border-radius: 7px; background: #fbfcfd; box-shadow: 0 3px 10px rgba(16, 47, 70, .08); }
		.metric-section h2 { margin: 0 0 6px; color: var(--heading); font-size: 21px; }
		.metric-section h3 { margin: 20px 0 10px; color: var(--heading); font-size: 15px; }
		.previous-run { margin: 0 0 16px; color: var(--muted); font-size: 13px; }
		.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin-bottom: 18px; }
		.card { padding: 16px; border: 1px solid var(--border); border-top: 4px solid #82939d; border-radius: 7px; background: var(--surface); }
		.card:nth-child(2) { border-color: var(--comparison); background: var(--surface-comparison); }
		.card:nth-child(2) .label, .card:nth-child(2) .value { color: var(--comparison-strong); }
		.regression-card { border-color: var(--danger); }
		.improvement-card { border-color: var(--success); }
		.label { display: block; margin-bottom: 8px; color: var(--muted); font-size: 12px; font-weight: 750; text-transform: uppercase; letter-spacing: .05em; }
		.value { color: var(--ink); font-size: 23px; font-weight: 700; }
		.text-value { font-size: 18px; }
		.wide-card { grid-column: 1 / -1; }
		.compact-grid { grid-template-columns: minmax(220px, 300px); margin-top: 14px; }
		.table-wrap { overflow-x: auto; margin-bottom: 14px; border: 1px solid var(--border); border-radius: 7px; }
		table { width: 100%; border-collapse: collapse; background: var(--surface); }
		th, td { padding: 11px 13px; border-right: 1px solid var(--border); border-bottom: 1px solid var(--border); text-align: right; }
		th:last-child, td:last-child { border-right: 0; }
		tbody tr:last-child td { border-bottom: 0; }
		tbody tr:nth-child(even) { background: var(--surface-subtle); }
		th:first-child, td:first-child { text-align: left; }
		thead th { background: var(--surface-muted); color: var(--ink-soft); font-size: 12px; font-weight: 750; text-transform: uppercase; letter-spacing: .05em; }
		thead th:nth-child(3), tbody td:nth-child(3) { background: var(--surface-comparison); color: var(--comparison-strong); font-weight: 700; }
		tbody td:nth-child(2) { font-weight: 600; }
		.variation-summary { margin: 8px 0 18px; color: var(--muted); }
		.structural-summary { margin: 2px 0 16px; color: var(--ink-soft); font-size: 17px; font-weight: 600; }
		.metric-section details { margin: 0 0 18px; padding: 12px 14px; border: 1px solid var(--border); border-radius: 6px; background: var(--surface); }
		.metric-section summary { cursor: pointer; color: var(--ink-soft); font-weight: 600; }
		.type-details { display: grid; grid-template-columns: max-content 1fr; gap: 7px 14px; margin: 14px 0 0; }
		.type-details dt { color: var(--muted); }
		.issue-group { --issue-group-color: var(--muted); overflow: hidden; padding: 0 !important; border-left: 4px solid var(--issue-group-color) !important; }
		.issue-group-new { --issue-group-color: var(--danger); }
		.issue-group-resolved { --issue-group-color: var(--success); }
		.issue-group-persistent { --issue-group-color: var(--warning); }
		.issue-group > summary { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 12px 14px; background: #f7f9fa; list-style-position: inside; }
		.issue-group[open] > summary { border-bottom: 1px solid var(--border); }
		.issue-group-note { color: var(--issue-group-color); font-size: 11px; font-weight: 750; }
		.issue-list { display: grid; gap: 9px; margin: 0; padding: 12px; list-style: none; }
		.issue-card { min-width: 0; padding: 12px; border: 1px solid #d6dfe3; border-radius: 7px; background: #fff; line-height: 1.4; }
		.issue-card-heading { display: flex; align-items: center; justify-content: space-between; gap: 10px; margin-bottom: 9px; }
		.issue-rule { color: var(--navy); font-size: 13px; line-height: 1.25; }
		.issue-impact { flex: 0 0 auto; padding: 3px 7px; border-radius: 999px; background: var(--surface-muted); color: var(--ink-soft); font-size: 10px; font-weight: 750; text-transform: capitalize; }
		.issue-target { display: grid; gap: 4px; }
		.issue-field-label { color: var(--muted); font-size: 9px; font-weight: 800; letter-spacing: .06em; text-transform: uppercase; }
		.issue-target code { display: block; max-width: 100%; padding: 7px 8px; border: 1px solid #d5dee2; border-radius: 5px; background: #f1f4f5; color: #075e5a; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 11px; line-height: 1.35; overflow-wrap: anywhere; white-space: pre-wrap; }
		.issue-description { margin-top: 8px !important; color: var(--ink-soft); font-size: 12px; line-height: 1.45; }
		.issue-empty { padding: 14px; color: var(--muted); font-size: 12px; }
		.heatmap-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px; margin-bottom: 18px; }
		.heatmap-grid .image-zoom-link { display: block; margin-top: 0; }
		figure img { display: block; width: 100%; max-height: 280px; object-fit: contain; border: 1px solid var(--border); border-radius: 6px; background: var(--surface); }
		figcaption { margin-top: 7px; color: var(--muted); text-align: center; }
		.explanation { padding: 16px; border-left: 4px solid var(--accent); border-radius: 5px; background: var(--surface-comparison); color: var(--ink-soft); line-height: 1.55; }
		.explanation p { margin: 0; }
		.comparison-warning { margin-bottom: 18px; padding: 14px 16px; border-left: 4px solid var(--warning); border-radius: 5px; background: var(--surface-warning); line-height: 1.5; }
		.metric-unavailable { border-left-color: var(--muted); }
		.baseline-empty { display: flex; align-items: center; gap: 14px; padding: 16px; border: 1px dashed var(--border); border-radius: 8px; background: var(--surface); }
		.baseline-empty-icon { display: grid; flex: 0 0 34px; width: 34px; height: 34px; place-items: center; border: 1px solid var(--muted); border-radius: 50%; color: var(--muted); font-size: 20px; }
		.baseline-empty strong { display: block; margin-bottom: 3px; font-size: 15px; }
		.baseline-empty p { color: var(--muted); line-height: 1.45; }
		.profile-overview { --goal-color: var(--muted); margin: 0 0 28px; padding: 22px; border: 1px solid var(--goal-color); border-top: 4px solid var(--goal-color); border-radius: 9px; background: var(--surface-comparison-block); }
		.profile-overview.status-achieved, .profile-card.status-achieved { --goal-color: var(--success); }
		.profile-overview.status-not-achieved, .profile-card.status-not-achieved { --goal-color: var(--danger); }
		.profile-overview.status-partial, .profile-card.status-partial { --goal-color: var(--warning); }
		.profile-overview.status-observed, .profile-card.status-observed, .profile-overview.status-unchanged, .profile-card.status-unchanged { --goal-color: var(--comparison); }
		.goal-summary { display: flex; align-items: flex-start; gap: 16px; margin-bottom: 20px; }
		.goal-icon { display: grid; flex: 0 0 44px; width: 44px; height: 44px; place-items: center; border: 2px solid var(--goal-color); border-radius: 50%; color: var(--goal-color); font-size: 25px; font-weight: 700; }
		.goal-summary .eyebrow { display: block; margin-bottom: 4px; color: var(--goal-color); font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
		.goal-summary h2 { margin-bottom: 5px; color: var(--heading); font-size: 21px; }
		.goal-summary p { color: var(--muted); line-height: 1.5; }
		.profile-summary-grid { display: grid; gap: 12px; }
		.profile-card { --goal-color: var(--muted); padding: 16px; border: 1px solid #cad5da; border-left: 4px solid var(--goal-color); border-radius: 8px; background: #fbfcfd; box-shadow: 0 2px 7px rgba(16, 47, 70, .06); }
		.profile-card-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; }
		.profile-card h3 { margin: 0 0 3px; color: var(--heading); font-size: 16px; }
		.profile-direction { color: var(--muted); font-size: 12px; }
		.status-pill { flex: 0 0 auto; padding: 4px 8px; border: 1px solid var(--goal-color); border-radius: 999px; color: var(--goal-color); font-size: 11px; font-weight: 700; }
		.outcome-track { display: flex; width: 100%; height: 9px; margin: 15px 0 8px; overflow: hidden; border-radius: 999px; background: var(--border); }
		.outcome-track span { flex: 1; min-width: 2px; }
		.track-aligned, .legend-aligned { background: var(--success); }
		.track-unchanged, .legend-unchanged { background: var(--muted); }
		.track-opposed, .legend-opposed { background: var(--danger); }
		.track-neutral { background: var(--muted); opacity: .5; }
		.outcome-legend, .track-key { display: flex; flex-wrap: wrap; gap: 8px 14px; color: var(--muted); font-size: 11px; }
		.outcome-legend i, .track-key i { display: inline-block; width: 8px; height: 8px; margin-right: 5px; border-radius: 50%; }
		.profile-metrics { margin-top: 15px; padding-top: 14px; border-top: 1px solid #dce3e6; }
		.profile-metrics-title { margin-bottom: 8px; color: var(--ink-soft); font-size: 11px; font-weight: 800; letter-spacing: .06em; text-transform: uppercase; }
		.profile-metrics ul { display: grid; grid-template-columns: repeat(auto-fit, minmax(245px, 1fr)); gap: 7px; list-style: none; }
		.profile-metric { display: flex; min-width: 0; align-items: center; justify-content: space-between; gap: 10px; padding: 8px 9px; border: 1px solid #d4dde1; border-radius: 6px; background: #fff; }
		.profile-metric-name { display: flex; min-width: 0; align-items: baseline; gap: 6px; color: var(--ink-soft); font-size: 11px; }
		.profile-metric-name strong { flex: 0 0 auto; color: var(--navy); font-family: 'SFMono-Regular', Consolas, monospace; font-size: 10px; }
		.profile-metric-impact { display: flex; flex: 0 0 auto; align-items: center; gap: 4px; font-size: 10px; font-weight: 700; }
		.profile-metric-impact i { display: grid; width: 15px; height: 15px; place-items: center; border-radius: 50%; color: #fff; font-size: 9px; font-style: normal; }
		.metric-aligned .profile-metric-impact { color: var(--success); }
		.metric-aligned .profile-metric-impact i { background: var(--success); }
		.metric-opposed .profile-metric-impact { color: var(--danger); }
		.metric-opposed .profile-metric-impact i { background: var(--danger); }
		.metric-unchanged .profile-metric-impact, .metric-not-comparable .profile-metric-impact { color: var(--muted); }
		.metric-unchanged .profile-metric-impact i, .metric-not-comparable .profile-metric-impact i { background: var(--muted); }
		.profile-reason { margin: 14px 0 0; line-height: 1.45; }
		.track-key { margin-top: 16px; padding-top: 14px; border-top: 1px solid var(--border); }
		.raw-metrics { margin: 6px 0 0; border: 1px solid var(--border); border-radius: 8px; background: var(--surface-subtle); }
		.raw-metrics > summary { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 17px 18px; cursor: pointer; color: var(--navy); font-size: 18px; font-weight: 700; list-style: none; }
		.raw-metrics > summary::-webkit-details-marker { display: none; }
		.raw-metrics-actions { display: flex; align-items: center; gap: 12px; }
		.raw-metrics-toggle { color: var(--accent-strong); font-size: 14px; transform-origin: center; transition: transform .18s ease; }
		.raw-metrics[open] .raw-metrics-toggle { transform: rotate(90deg); }
		.raw-metrics > summary:hover { background: var(--surface-muted); }
		.raw-metrics > summary:focus-visible { outline: 2px solid var(--accent); outline-offset: -3px; }
		.raw-metrics[open] > summary { border-bottom: 1px solid var(--border); }
		.raw-metrics-content { padding: 18px; }
		.results-heading { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin: 0 0 12px; }
		.results-heading h2 { color: var(--navy); font-size: 20px; }
		.results-count { padding: 5px 9px; border: 1px solid var(--border); border-radius: 999px; background: var(--surface-muted); color: var(--ink-soft); font-size: 12px; font-weight: 750; }
		@media (max-width: 620px) {
			body { padding: 12px; }
			.header, .content { padding: 22px 18px; }
			.section-heading { align-items: flex-start; flex-direction: column; }
			.comparison-summary { grid-template-columns: minmax(0, 1fr) auto; }
			.comparison-preview { grid-column: 1 / -1; grid-row: 2; }
			.comparison-toggle { grid-column: 2; grid-row: 1; }
			.run-pair { grid-template-columns: 1fr; }
			.run-arrow { width: auto; height: 20px; transform: rotate(90deg); }
			.profile-card-heading { display: block; }
			.status-pill { display: inline-block; margin-top: 10px; }
			.profile-ai-heading { grid-template-columns: auto 1fr; }
			.profile-ai-status { grid-column: 1 / -1; width: fit-content; }
			.suggestions-heading { align-items: flex-start; flex-direction: column; }
			.custom-ai-badges { gap: 5px; }
			.custom-finding-heading { align-items: flex-start; flex-direction: column; }
			.metric-chips { justify-content: flex-start; }
		}
		.metric-result {
			background: var(--surface-subtle);
			border: 1px solid var(--border);
			border-left: 5px solid var(--accent);
			padding: 20px;
			margin-bottom: 20px;
			border-radius: 6px;
			transition: border-color .2s, box-shadow .2s;
		}
		.metric-result:hover {
			border-color: #b8cbc9;
			border-left-color: var(--accent-strong);
			box-shadow: 0 5px 14px rgba(16, 47, 70, .14);
		}
		.metric-result h3 {
			color: var(--navy);
			font-size: 19px;
			font-weight: 700;
			margin-bottom: 15px;
		}
		.result-values {
			display: flex;
			flex-direction: column;
			gap: 10px;
		}
		.result-item {
			background: var(--surface);
			padding: 12px 15px;
			border-radius: 4px;
			font-size: 15px;
			font-weight: 500;
			border: 1px solid var(--border);
			line-height: 1.5;
		}
		.result-item strong {
			color: var(--accent-strong);
			margin-right: 8px;
		}
		.image-zoom-link { position: relative; display: inline-block; max-width: 100%; margin-top: 10px; border-radius: 6px; }
		.image-zoom-link::after { content: 'Open full size ↗'; position: absolute; right: 8px; bottom: 8px; padding: 5px 8px; border-radius: 5px; background: rgba(16, 47, 70, .88); color: #fff; font-size: 11px; font-weight: 700; opacity: 0; transform: translateY(3px); transition: opacity .18s ease, transform .18s ease; }
		.image-zoom-link:hover::after, .image-zoom-link:focus-visible::after { opacity: 1; transform: translateY(0); }
		.image-zoom-link:focus-visible { outline: 3px solid var(--accent); outline-offset: 3px; }
		.result-image { display: block; max-width: 100%; border: 1px solid var(--border); border-radius: 6px; }
		.result-json { margin-top: 10px; padding: 12px; overflow-x: auto; border: 1px solid var(--border); border-radius: 5px; background: var(--surface-muted); color: var(--ink-soft); font-size: 12px; line-height: 1.45; white-space: pre-wrap; word-break: break-word; }
		.empty-state {
			text-align: center;
			padding: 40px 20px;
			color: var(--muted);
		}
		.empty-state p {
			font-size: 16px;
			margin-bottom: 10px;
		}
		@media (prefers-reduced-motion: reduce) {
			.metric-result, .raw-metrics-toggle, .comparison-toggle, .image-zoom-link::after { transition: none; }
		}
	</style>
</head>
<body>
	<div class="container">
		<div class="header">
			<h1>Evaluation Results</h1>
			<p class="assessment-status ${isComplete ? 'complete' : 'in-progress'}"><span class="status-dot" aria-hidden="true"></span>Web UI Assessment ${isComplete ? 'Complete' : 'in Progress...'}</p>
			<div class="url-display">Target · ${renderTargetLink(url)}</div>
		</div>
		<div class="content">
			${explanationHtml}
			${comparison?.profileOverviewHtml ?? ''}
			${comparisonHtml}
			${rawMetricsHtml}
		</div>
	</div>
</body>
</html>`;
}
